describe('ESKIMI website testing', () => {
    beforeEach(() => {
        cy.visit('https://dsp.eskimi.com/admin?function=campaigns&method=index')

    })


    it('Update Contact person full name, contact person email, contact person phone ', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get('#navSettingsMenu').click()
        cy.get('.dropdown-menu > [href="/admin?function=account&method=edit_personal_info"]').click()
        cy.get('#form-step-box-i-0 > .step-body > :nth-child(7) > .form-control').clear().type("Jonas Jonaitis").should('have.value', 'Jonas Jonaitis')
        cy.get('#form-step-box-i-0 > .step-body > :nth-child(8) > .form-control').clear().type('nopitih608@dogemn.com').should('have.value', "nopitih608@dogemn.com")
        cy.get(':nth-child(9) > .form-control').clear().type("+370 670 72896").should('have.value', "+370 670 72896")
        cy.get('.btn-primary').click()
    })
    it('Update Billing information', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get('#navSettingsMenu').click()
        cy.get('.dropdown-menu > [href="/admin?function=account&method=edit_personal_info"]').click()
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(3) > .form-control').type("55423").should("have.value", "55423")
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(4) > .form-control').type("keturipenki").should("have.value", "keturipenki")
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(5) > .form-control').type("Du gaideliai").should("have.value", "Du gaideliai")
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(6) > .form-control').type("nopitih608@dogemn.com").should("have.value", "nopitih608@dogemn.com")
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(7) > .form-control').type("+355 68 294 7409").should("have.value", "+355 68 294 7409")
        cy.get('#form-step-box-i-1 > .step-body > :nth-child(8) > .form-control').type("30").should("have.value", "30")
        cy.get('.btn-primary').click()
    })
    it('Change to weak password', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get('#navSettingsMenu').click()
        cy.get('.dropdown-menu > [href="/admin?function=account&method=edit_personal_info"]').click()
        cy.get("#yourPassword").type(Cypress.env('password'))
        cy.get("#password").type(Cypress.env('password_weak'))
        cy.get('.password-strength-indicator').should("have.text", "weak")
        cy.get('#form-step-box-i-0 > .step-body > :nth-child(4) > .form-control').type(Cypress.env('password_weak'))
        cy.get('.btn-primary').click()
        cy.get('.alert').should('be.visible')

    })
    it('Change to strong password', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password_weak'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get('#navSettingsMenu').click()
        cy.get('.dropdown-menu > [href="/admin?function=account&method=edit_personal_info"]').click()
        cy.get("#yourPassword").type(Cypress.env('password_weak'))
        cy.get("#password").type(Cypress.env('password_strong'))
        cy.get('.password-strength-indicator').should('have.text', "strong")
        cy.get('#form-step-box-i-0 > .step-body > :nth-child(4) > .form-control').type(Cypress.env('password_strong'))
        cy.get('.btn-primary').click()
        cy.get('.alert').should('be.visible')
        cy.get("#yourPassword").type(Cypress.env('password_strong'))
        cy.get("#password").type(Cypress.env('password'))
        cy.get('#form-step-box-i-0 > .step-body > :nth-child(4) > .form-control').type(Cypress.env('password'))
        cy.get('.btn-primary').click()
        cy.get('.alert').should('be.visible')

    })
    it('Create a campgain group with just Campaign name in DRAFT. Check if it is saved as DRAFT and the same name', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password_strong'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get(':nth-child(1) > .btn').click()
        cy.get('#name').type("TestQA").should("have.value", "TestQA")
        // cy.get('#form-step-box-i-7 > .step-body > :nth-child(2) > .select2 > .selection > .select2-selection > .select2-selection__arrow').click()
        cy.get('#form-step-box-i-7').first('.select2-selection__arrow').click()
        cy.get('ul.select2-results__options').contains('Native').click()
        cy.get('.btn-danger').click()
        cy.wait(700)
        cy.get('.btn-danger').click()
        cy.get('.btn-info').click()
        cy.get('.badge').contains("Dra.")
        cy.get('.large-text').contains("TestQA")
        cy.get('div.large-text').contains('TestQA').parentsUntil('.table').find('i.fas.fa-ellipsis-v').click()
        // cy.get('i.fas.fa-ellipsis-v').click()
        cy.get('.dropdown > .dropdown-menu > [title="Delete"]').click()
        cy.get('.btn-success').click()
    })

    it('Create a campgain group with just Campaign name and saved banner in DRAFT. Check if it is saved as DRAFT and the same name', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password_strong'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get(':nth-child(1) > .btn').click()
        cy.get('#name').type("TestQA").should("have.value", "TestQA")
        cy.get('#form-step-box-i-7').first('.select2-selection__arrow').click()
        cy.get('ul.select2-results__options').contains('Banner').click()
        cy.get('.btn-info').click()
        cy.get('.badge').contains("Dra.")
        cy.get('.large-text').contains("TestQA")
        // cy.get('th.ad-pad.text-center.sorting_asc').select('#tooltip').should('have.value', 'banner')
        cy.get('div.large-text').contains('TestQA').parentsUntil('.table').find('i.fas.fa-ellipsis-v').click()
        // cy.get('#dropdown-toggle').select('dropdown').click()
        // cy.get('.dropdown > .dropdown-menu > [title="Delete"]').click()
        cy.get('.dropdown > .dropdown-menu > [title="Delete"]').click()
        cy.get('.btn-success').click()
    })
    it('Create a campgain group with all required fields filled in DRAFT. Check if it is saved as DRAFT and the same name', () => {
        cy.get('#username').type(Cypress.env('username'))
        cy.get('#password').type(Cypress.env('password_strong'))
        cy.get('.btn-glow').click()
        cy.contains("Campaign groups")
        cy.get(':nth-child(1) > .btn').click()
        cy.get('#name').type("TestQA").should("have.value", "TestQA")
        cy.get('#form-step-box-i-7').first('.select2-selection__arrow').click()
        cy.get('ul.select2-results__options').contains('Banner').click()
        // cy.get('.date-box > :nth-child(2) > .fas').select('d_20230420 > a > span')
        cy.get('.date-box > :nth-child(2) > .fas').click()
        cy.get('.d_20230427 > a > span').click()
        cy.get('.js-datepicker-apply').click()
        cy.get('#bid_currency').type("0").should('have.value', "0")
        cy.get('#budget_daily_currency').type("100").should('have.value', "100")
        cy.get('#budget_total_currency').type('500').should('have.value', "500")
        cy.get('.step-body > :nth-child(1) > .mselect > .selection > .mselect-selection > .mselect-selection__arrow').click()
        cy.get('.select-items > :nth-child(3) > label').click()
        cy.get('.modal-footer > .btn-primary').click()
        cy.get('.js-campaign-click-url-fields > :nth-child(1) > .select2 > .selection > .select2-selection > .select2-selection__arrow').click()
        cy.get('.select2-results__option').contains('Android App download').click()
        cy.get('#form-step-box-i-12 > .step-body > :nth-child(2) > .select2 > .selection > .select2-selection > .select2-selection__arrow > b').click()
        cy.get('.select2-search__field').type("yourproduct.com")
        cy.get('#html-creatives > .mselect > .selection > .mselect-selection > .mselect-selection__rendered').click()
        cy.get('.select-item > label').click()
        cy.get('.modal-footer > .btn-primary').contains('SELECT 1').click()
        cy.get('.btn-info').contains("Draft").click()
        cy.get('.badge').contains("Dra.")
        cy.get('.large-text').contains("TestQA")
        cy.get('div.large-text').contains('TestQA').parentsUntil('.table').find('i.fas.fa-ellipsis-v').click()
        cy.get('.dropdown > .dropdown-menu > [title="Delete"]').click()
        cy.get('.btn-success').click()
        

    })
})